# Generated by Django 3.2.16 on 2023-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_registration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=500)),
                ('post_desc', models.CharField(default='', max_length=500)),
                ('post_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
