# Generated by Django 3.2.16 on 2023-01-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='full_name',
            new_name='f_name',
        ),
    ]
