# Generated by Django 3.2.16 on 2023-01-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
