# Generated by Django 3.2.16 on 2023-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230124_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='member',
            name='f_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='l_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='', max_length=120),
        ),
    ]
